import React, { useState, useRef, useEffect, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { FaEye, FaDownload } from 'react-icons/fa';
import Table from '../../../../shared/table/Table';
import CoordinatorTicketFilter from '../../../components/filters/CoordinatorAdminTicketManagementFilter';
import reportTickets from '../../../../mock-data/reportTickets.json';
import Tabs from '../../../../shared/components/Tabs';

const CoordinatorAdminTicketReports = () => {
  const tabs = [
    { label: 'All', value: 'all' },
    { label: 'Daily', value: 'daily' },
    { label: 'Weekly', value: 'weekly' },
    { label: 'Monthly', value: 'monthly' },
    { label: 'Yearly', value: 'yearly' },
  ];

  const [activeTab, setActiveTab] = useState(tabs[0]?.value || 'all');
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [activeFilters, setActiveFilters] = useState({
    status: null,
    priority: null,
    category: null,
    subCategory: null,
    slaStatus: null,
    startDate: "",
    endDate: "",
  });
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const [showFilter, setShowFilter] = useState(false);
  const navigate = useNavigate();
  const reports = useMemo(() => reportTickets, []);

  const FilterComponent = () => (
    <CoordinatorTicketFilter
      key={showFilter ? "filter-shown" : "filter-hidden"}
      preset="ticketManagement"
      initialShow={showFilter}
      onApply={setActiveFilters}
      onReset={() => {
        setActiveFilters({
          status: null,
          priority: null,
          category: null,
          subCategory: null,
          slaStatus: null,
          startDate: "",
          endDate: "",
        });
        setCurrentPage(1);
      }}
      initialFilters={activeFilters}
    />
  );

  const columns = [
    { key: 'reportName', label: 'Report Name', skeletonWidth: '120px' },
    {
      key: 'period',
      label: 'Period',
      skeletonWidth: '80px',
      render: (val) => {
        const colors = {
          Daily: { bg: '#E0E7FF', text: '#4F46E5' },
          Weekly: { bg: '#F3E8FF', text: '#7C3AED' },
          Monthly: { bg: '#DCFCE7', text: '#22C55E' },
          Yearly: { bg: '#FEF3C7', text: '#F59E0B' },
        };
        const color = colors[val] || { bg: '#e5e7eb', text: '#1f2937' };
        return (
          <span style={{
            backgroundColor: color.bg,
            color: color.text,
            padding: '4px 12px',
            borderRadius: '9999px',
            fontSize: '12px',
            fontWeight: 500,
          }}>
            {val}
          </span>
        );
      },
    },
    { key: 'dateGenerated', label: 'Date Generated', skeletonWidth: '130px' },
    {
      key: 'status',
      label: 'Status',
      skeletonWidth: '80px',
      render: (val) => (
        <span style={{
          backgroundColor: '#DCFCE7',
          color: '#22C55E',
          padding: '4px 12px',
          borderRadius: '9999px',
          fontSize: '12px',
          fontWeight: 500,
        }}>
          {val}
        </span>
      ),
    },
    { key: 'generatedBy', label: 'Generated By', skeletonWidth: '100px' },
    {
      key: 'totalTickets',
      label: 'Total Tickets',
      skeletonWidth: '80px',
      render: (val) => <span style={{ fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'resolved',
      label: 'Resolved',
      skeletonWidth: '80px',
      render: (val) => <span style={{ color: '#22C55E', fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'pending',
      label: 'Pending',
      skeletonWidth: '80px',
      render: (val) => <span style={{ color: '#EF4444', fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'actions',
      label: 'Actions',
      skeletonWidth: '80px',
      render: (val, row) => (
        <>
          <button
            title="View"
            style={{ padding: '6px 10px', background: '#f9f9f9', border: '1px solid #ccc', borderRadius: '4px', cursor: 'pointer' }}
            onClick={() => {
              const tf = String(lastActiveRef.current || 'daily').toLowerCase();
              const url = `/admin/reports/ticket/view?timeframe=${encodeURIComponent(tf)}&reportId=${encodeURIComponent(row.id || '')}&autoGen=1`;
              try {
                navigate(url);
              } catch (e) {
                window.location.href = url;
              }
            }}
          >
            <FaEye size={12} />
          </button>
          <button
            title="Export"
            style={{ padding: '6px 10px', background: '#f9f9f9', border: '1px solid #ccc', borderRadius: '4px', cursor: 'pointer' }}
            onClick={() => console.log('Export report:', row)}
          >
            <FaDownload size={12} />
          </button>
        </>
      ),
    },
  ];

  useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm, activeFilters]);

  return (
    <>
      <div style={{ marginTop: 12, marginBottom: 8 }}>
        <Tabs tabs={tabs} active={activeTab} onChange={setActiveTab} />
      </div>
      <Table
        variant="default"
        data={(() => {
          const periodFilter = activeTab === 'all' ? null : activeTab.toLowerCase();

          const filtered = (reports || []).filter(item => {
            if (periodFilter) {
              const itemPeriod = item.period ? String(item.period).toLowerCase() : '';
              if (itemPeriod !== periodFilter) return false;
            }

            const matchesSearch = searchTerm
              ? Object.values(item).some(val => 
                  val && String(val).toLowerCase().includes(searchTerm.toLowerCase())
                )
              : true;
            if (!matchesSearch) return false;

            if (activeFilters.status) {
              const filterStatus = activeFilters.status.label || activeFilters.status;
              const itemStatus = item.status ? String(item.status).toLowerCase() : '';
              if (filterStatus && itemStatus !== String(filterStatus).toLowerCase()) {
                return false;
              }
            }

            if (activeFilters.priority) {
              const filterPriority = activeFilters.priority.label || activeFilters.priority;
              const itemPriority = item.priority ? String(item.priority).toLowerCase() : '';
              if (filterPriority && itemPriority !== String(filterPriority).toLowerCase()) {
                return false;
              }
            }

            if (activeFilters.category) {
              const filterCategory = activeFilters.category.label || activeFilters.category;
              const itemCategory = item.category ? String(item.category).toLowerCase() : '';
              if (filterCategory && itemCategory !== String(filterCategory).toLowerCase()) {
                return false;
              }
            }

            if (activeFilters.subCategory) {
              const filterSubCategory = activeFilters.subCategory.label || activeFilters.subCategory;
              const itemSubCategory = item.subCategory ? String(item.subCategory).toLowerCase() : '';
              if (filterSubCategory && itemSubCategory !== String(filterSubCategory).toLowerCase()) {
                return false;
              }
            }

            if (activeFilters.slaStatus) {
              const filterSLA = activeFilters.slaStatus.label || activeFilters.slaStatus;
              const itemSLA = item.slaStatus ? String(item.slaStatus).toLowerCase() : '';
              if (filterSLA && itemSLA !== String(filterSLA).toLowerCase()) {
                return false;
              }
            }

            if (activeFilters.startDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const start = new Date(activeFilters.startDate);
                if (!isNaN(itemDate.getTime()) && !isNaN(start.getTime())) {
                  const itemDateOnly = new Date(itemDate.getFullYear(), itemDate.getMonth(), itemDate.getDate());
                  const startDateOnly = new Date(start.getFullYear(), start.getMonth(), start.getDate());
                  if (itemDateOnly < startDateOnly) return false;
                }
              } catch (e) {}
            }

            if (activeFilters.endDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const end = new Date(activeFilters.endDate);
                if (!isNaN(itemDate.getTime()) && !isNaN(end.getTime())) {
                  const itemDateOnly = new Date(itemDate.getFullYear(), itemDate.getMonth(), itemDate.getDate());
                  const endDateOnly = new Date(end.getFullYear(), end.getMonth(), end.getDate());
                  if (itemDateOnly > endDateOnly) return false;
                }
              } catch (e) {}
            }

            return true;
          });

          return filtered.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);
        })()}
        columns={columns}
        title="Ticket Reports"
        searchable
        searchPlaceholder="Search..."
        searchValue={searchTerm}
        onSearchChange={(e) => setSearchTerm(e.target.value)}
        filterComponent={FilterComponent}
        showFilter={showFilter}
        onShowFilterChange={setShowFilter}
        currentPage={currentPage}
        pageSize={itemsPerPage}
        totalItems={(() => {
          const periodFilter = activeTab === 'all' ? null : activeTab.toLowerCase();

          return (reports || []).filter(item => {
            if (periodFilter) {
              const itemPeriod = item.period ? String(item.period).toLowerCase() : '';
              if (itemPeriod !== periodFilter) return false;
            }

            const matchesSearch = searchTerm
              ? Object.values(item).some(val => 
                  val && String(val).toLowerCase().includes(searchTerm.toLowerCase())
                )
              : true;
            if (!matchesSearch) return false;

            if (activeFilters.status) {
              const filterStatus = activeFilters.status.label || activeFilters.status;
              const itemStatus = item.status ? String(item.status).toLowerCase() : '';
              if (filterStatus && itemStatus !== String(filterStatus).toLowerCase()) {
                return false;
              }
            }

            if (activeFilters.priority) {
              const filterPriority = activeFilters.priority.label || activeFilters.priority;
              const itemPriority = item.priority ? String(item.priority).toLowerCase() : '';
              if (filterPriority && itemPriority !== String(filterPriority).toLowerCase()) {
                return false;
              }
            }

            if (activeFilters.category) {
              const filterCategory = activeFilters.category.label || activeFilters.category;
              const itemCategory = item.category ? String(item.category).toLowerCase() : '';
              if (filterCategory && itemCategory !== String(filterCategory).toLowerCase()) {
                return false;
              }
            }

            if (activeFilters.subCategory) {
              const filterSubCategory = activeFilters.subCategory.label || activeFilters.subCategory;
              const itemSubCategory = item.subCategory ? String(item.subCategory).toLowerCase() : '';
              if (filterSubCategory && itemSubCategory !== String(filterSubCategory).toLowerCase()) {
                return false;
              }
            }

            if (activeFilters.slaStatus) {
              const filterSLA = activeFilters.slaStatus.label || activeFilters.slaStatus;
              const itemSLA = item.slaStatus ? String(item.slaStatus).toLowerCase() : '';
              if (filterSLA && itemSLA !== String(filterSLA).toLowerCase()) {
                return false;
              }
            }

            if (activeFilters.startDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const start = new Date(activeFilters.startDate);
                if (!isNaN(itemDate.getTime()) && !isNaN(start.getTime())) {
                  const itemDateOnly = new Date(itemDate.getFullYear(), itemDate.getMonth(), itemDate.getDate());
                  const startDateOnly = new Date(start.getFullYear(), start.getMonth(), start.getDate());
                  if (itemDateOnly < startDateOnly) return false;
                }
              } catch (e) {}
            }

            if (activeFilters.endDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const end = new Date(activeFilters.endDate);
                if (!isNaN(itemDate.getTime()) && !isNaN(end.getTime())) {
                  const itemDateOnly = new Date(itemDate.getFullYear(), itemDate.getMonth(), itemDate.getDate());
                  const endDateOnly = new Date(end.getFullYear(), end.getMonth(), end.getDate());
                  if (itemDateOnly > endDateOnly) return false;
                }
              } catch (e) {}
            }

            return true;
          }).length;
        })()}
        onPageChange={setCurrentPage}
        onPageSizeChange={setItemsPerPage}
        isLoading={false}
        emptyMessage="No ticket reports found."
      />
    </>
  );
};

export default CoordinatorAdminTicketReports;