import React, { useState, useEffect, useRef } from 'react';
import { FaEye, FaDownload } from 'react-icons/fa';
import CoordinatorAdminReportsLayout from '../CoordinatorAdminReportsLayout';
import InputField from '../../../../shared/components/InputField';
import layoutStyles from '../CoordinatorAdminReportsLayout.module.css';
import ticketStyles from '../../ticket-management/CoordinatorAdminTicketManagement.module.css';
import TablePagination from '../../../../shared/table/TablePagination';
import reportCSATPerformance from '../../../../mock-data/reportCSATPerformance.json';
import FilterPanel from '../../../../shared/table/FilterPanel';

const CoordinatorAdminCSATPerformanceReports = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [activeFilters, setActiveFilters] = useState({ rating: null, startDate: '', endDate: '' });
  const [itemsPerPage, setItemsPerPage] = useState(10);

  // Apply search + CSAT-specific filters (rating + date range)
  const filteredData = reportCSATPerformance.filter(item => {
    const matchesSearch = searchTerm
      ? Object.values(item).some(val => String(val).toLowerCase().includes(searchTerm.toLowerCase()))
      : true;
    if (!matchesSearch) return false;

    if (activeFilters.rating) {
      // reports may have averageCSAT; compare rounded value to rating
      const avg = Math.round(Number(item.averageCSAT || 0));
      if (avg !== Number(activeFilters.rating)) return false;
    }

    if (activeFilters.startDate) {
      try {
        const itemDate = new Date(item.dateGenerated);
        const start = new Date(activeFilters.startDate);
        if (itemDate < start) return false;
      } catch (e) {}
    }
    if (activeFilters.endDate) {
      try {
        const itemDate = new Date(item.dateGenerated);
        const end = new Date(activeFilters.endDate);
        end.setHours(23,59,59,999);
        if (itemDate > end) return false;
      } catch (e) {}
    }

    return true;
  });

  // pagination and filtering per-tab handled in render function
  const paginatedData = filteredData.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);
  const columns = [
    { key: 'reportName', label: 'Report Name' },
    {
      key: 'period',
      label: 'Period',
      render: (val) => {
        const colors = {
          Daily: { bg: '#E0E7FF', text: '#4F46E5' },
          Weekly: { bg: '#F3E8FF', text: '#7C3AED' },
          Monthly: { bg: '#DCFCE7', text: '#22C55E' },
          Yearly: { bg: '#FEF3C7', text: '#F59E0B' },
        };
        const color = colors[val] || { bg: '#e5e7eb', text: '#1f2937' };
        return (
          <span style={{
            backgroundColor: color.bg,
            color: color.text,
            padding: '4px 12px',
            borderRadius: '9999px',
            fontSize: '12px',
            fontWeight: 500,
          }}>
            {val}
          </span>
        );
      },
    },
    { key: 'dateGenerated', label: 'Date Generated' },
    {
      key: 'status',
      label: 'Status',
      render: (val) => (
        <span style={{
          backgroundColor: '#DCFCE7',
          color: '#22C55E',
          padding: '4px 12px',
          borderRadius: '9999px',
          fontSize: '12px',
          fontWeight: 500,
        }}>
          {val}
        </span>
      ),
    },
    { key: 'generatedBy', label: 'Generated By' },
    {
      key: 'totalResponses',
      label: 'Total Responses',
      render: (val) => <span style={{ fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'averageCSAT',
      label: 'Average CSAT',
      render: (val) => <span style={{ color: '#8B5CF6', fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'satisfied',
      label: 'Satisfied',
      render: (val) => <span style={{ color: '#22C55E', fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'unsatisfied',
      label: 'Unsatisfied',
      render: (val) => <span style={{ color: '#EF4444', fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'id',
        label: 'Actions',
        render: (val, row) => (
        <div className={ticketStyles.actionButtonCont}>
          <button
            title="View"
            className={ticketStyles.actionButton}
            onClick={() => console.log('View report:', row)}
          >
            <FaEye />
          </button>
          <button
            title="Export"
            className={ticketStyles.actionButton}
            onClick={() => console.log('Export report:', row)}
          >
            <FaDownload />
          </button>
        </div>
        ),
    },
  ];

  // Reset page when filters/search change
  useEffect(() => setCurrentPage(1), [searchTerm, activeFilters]);

  const lastActiveRef = useRef(null);

  return (
    <CoordinatorAdminReportsLayout title="CSAT Performance Reports" filter={<FilterPanel
      fields={['rating','startDate','endDate']}
      hideToggleButton={true}
      onApply={setActiveFilters}
      onReset={() => setActiveFilters({ rating: null, startDate: '', endDate: '' })}
      initialFilters={activeFilters}
    />}>
      {(active) => {
        // reset page when active tab changes
        if (lastActiveRef.current !== active) {
          setTimeout(() => setCurrentPage(1), 0);
          lastActiveRef.current = active;
        }
        const periodFilter = active === 'all' ? null : active;

        const filtered = reportCSATPerformance.filter(item => {
          if (periodFilter) {
            if (!item.period || String(item.period).toLowerCase() !== String(periodFilter).toLowerCase()) return false;
          }

          const matchesSearch = searchTerm
            ? Object.values(item).some(val => String(val).toLowerCase().includes(searchTerm.toLowerCase()))
            : true;
          if (!matchesSearch) return false;

          if (activeFilters.rating) {
            const avg = Math.round(Number(item.averageCSAT || 0));
            if (avg !== Number(activeFilters.rating)) return false;
          }

          if (activeFilters.startDate) {
            try {
              const itemDate = new Date(item.dateGenerated);
              const start = new Date(activeFilters.startDate);
              if (itemDate < start) return false;
            } catch (e) {}
          }
          if (activeFilters.endDate) {
            try {
              const itemDate = new Date(item.dateGenerated);
              const end = new Date(activeFilters.endDate);
              end.setHours(23,59,59,999);
              if (itemDate > end) return false;
            } catch (e) {}
          }

          return true;
        });

        const page = filtered.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

        return (
          <>
            <div className={ticketStyles.tableHeader}>
              <h2>CSAT Performance Reports</h2>
              <div className={ticketStyles.tableActions}>
                <InputField
                  placeholder="Search..."
                  value={searchTerm}
                  onChange={e => setSearchTerm(e.target.value)}
                  inputStyle={{ width: '260px' }}
                />
              </div>
            </div>

            <div className={ticketStyles.tableWrapper}>
              <table className={ticketStyles.table}>
                <thead>
                  <tr>
                    {columns.map(col => (
                      <th key={col.key}>{col.label}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {page.length === 0 ? (
                    <tr>
                      <td colSpan={columns.length} style={{ textAlign: 'center', padding: '40px', color: '#6b7280', fontStyle: 'italic' }}>
                        No data found.
                      </td>
                    </tr>
                  ) : (
                    page.map((row, idx) => (
                      <tr
                        key={idx}
                        style={{ borderBottom: '1px solid #e5e7eb', transition: '0.2s' }}
                        onMouseEnter={e => e.currentTarget.style.backgroundColor = '#f9fafb'}
                        onMouseLeave={e => e.currentTarget.style.backgroundColor = 'transparent'}
                      >
                        {columns.map(col => (
                          <td key={col.key} style={{ padding: '12px 16px', color: '#1f2937' }}>
                            {col.render ? col.render(row[col.key], row) : row[col.key]}
                          </td>
                        ))}
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            <div className={ticketStyles.tablePagination}>
              <TablePagination
                currentPage={currentPage}
                totalItems={filtered.length}
                initialItemsPerPage={itemsPerPage}
                onPageChange={setCurrentPage}
                onItemsPerPageChange={setItemsPerPage}
                alwaysShow={true}
              />
            </div>
          </>
        );
      }}
    </CoordinatorAdminReportsLayout>
  );
};

export default CoordinatorAdminCSATPerformanceReports;
