import React, { useState, useEffect, useRef, useMemo } from 'react';
import { FaEye, FaDownload } from 'react-icons/fa';
import Table from '../../../../shared/table/Table';
import FilterPanel from '../../../../shared/table/FilterPanel';
import reportCSATPerformance from '../../../../mock-data/reportCSATPerformance.json';
import Tabs from '../../../../shared/components/Tabs';

const CoordinatorAdminCSATPerformanceReports = () => {
  const tabs = [
    { label: 'All', value: 'all' },
    { label: 'Daily', value: 'daily' },
    { label: 'Weekly', value: 'weekly' },
    { label: 'Monthly', value: 'monthly' },
    { label: 'Yearly', value: 'yearly' },
  ];

  const [activeTab, setActiveTab] = useState(tabs[0]?.value || 'all');
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [activeFilters, setActiveFilters] = useState({ rating: null, startDate: '', endDate: '' });
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const [showFilter, setShowFilter] = useState(false);
  const reports = useMemo(() => reportCSATPerformance, []);

  const FilterComponent = () => (
    <FilterPanel
      fields={['rating', 'startDate', 'endDate']}
      onApply={setActiveFilters}
      onReset={() => {
        setActiveFilters({ rating: null, startDate: '', endDate: '' });
        setCurrentPage(1);
      }}
      initialFilters={activeFilters}
    />
  );

  // Apply search + CSAT-specific filters (rating + date range)
  const filteredData = (reportCSATPerformance || []).filter(item => {
    const matchesSearch = searchTerm
      ? Object.values(item).some(val => String(val).toLowerCase().includes(searchTerm.toLowerCase()))
      : true;
    if (!matchesSearch) return false;

    if (activeFilters.rating) {
      // reports may have averageCSAT; compare rounded value to rating
      const avg = Math.round(Number(item.averageCSAT || 0));
      if (avg !== Number(activeFilters.rating)) return false;
    }

    if (activeFilters.startDate) {
      try {
        const itemDate = new Date(item.dateGenerated);
        const start = new Date(activeFilters.startDate);
        if (itemDate < start) return false;
      } catch (e) {}
    }
    if (activeFilters.endDate) {
      try {
        const itemDate = new Date(item.dateGenerated);
        const end = new Date(activeFilters.endDate);
        end.setHours(23,59,59,999);
        if (itemDate > end) return false;
      } catch (e) {}
    }

    return true;
  });

  // pagination and filtering per-tab handled in render function
  const paginatedData = filteredData.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);
  
  const columns = [
    { key: 'reportName', label: 'Report Name', skeletonWidth: '120px' },
    {
      key: 'period',
      label: 'Period',
      skeletonWidth: '80px',
      render: (val) => {
        const colors = {
          Daily: { bg: '#E0E7FF', text: '#4F46E5' },
          Weekly: { bg: '#F3E8FF', text: '#7C3AED' },
          Monthly: { bg: '#DCFCE7', text: '#22C55E' },
          Yearly: { bg: '#FEF3C7', text: '#F59E0B' },
        };
        const color = colors[val] || { bg: '#e5e7eb', text: '#1f2937' };
        return (
          <span style={{
            backgroundColor: color.bg,
            color: color.text,
            padding: '4px 12px',
            borderRadius: '9999px',
            fontSize: '12px',
            fontWeight: 500,
          }}>
            {val}
          </span>
        );
      },
    },
    { key: 'dateGenerated', label: 'Date Generated', skeletonWidth: '130px' },
    {
      key: 'status',
      label: 'Status',
      skeletonWidth: '80px',
      render: (val) => (
        <span style={{
          backgroundColor: '#DCFCE7',
          color: '#22C55E',
          padding: '4px 12px',
          borderRadius: '9999px',
          fontSize: '12px',
          fontWeight: 500,
        }}>
          {val}
        </span>
      ),
    },
    { key: 'generatedBy', label: 'Generated By', skeletonWidth: '100px' },
    {
      key: 'totalResponses',
      label: 'Total Responses',
      skeletonWidth: '80px',
      render: (val) => <span style={{ fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'averageCSAT',
      label: 'Average CSAT',
      skeletonWidth: '100px',
      render: (val) => <span style={{ color: '#8B5CF6', fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'satisfied',
      label: 'Satisfied',
      skeletonWidth: '80px',
      render: (val) => <span style={{ color: '#22C55E', fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'unsatisfied',
      label: 'Unsatisfied',
      skeletonWidth: '80px',
      render: (val) => <span style={{ color: '#EF4444', fontWeight: 'bold' }}>{val}</span>,
    },
    {
      key: 'actions',
      label: 'Actions',
      skeletonWidth: '80px',
      render: (val, row) => (
        <>
          <button
            title="View"
            style={{ padding: '6px 10px', background: '#f9f9f9', border: '1px solid #ccc', borderRadius: '4px', cursor: 'pointer' }}
            onClick={() => console.log('View report:', row)}
          >
            <FaEye size={12} />
          </button>
          <button
            title="Export"
            style={{ padding: '6px 10px', background: '#f9f9f9', border: '1px solid #ccc', borderRadius: '4px', cursor: 'pointer' }}
            onClick={() => console.log('Export report:', row)}
          >
            <FaDownload size={12} />
          </button>
        </>
      ),
    },
  ];

  // Reset page when filters/search change
  useEffect(() => setCurrentPage(1), [searchTerm, activeFilters]);

  return (
    <>
      <div style={{ marginTop: 12, marginBottom: 8 }}>
        <Tabs tabs={tabs} active={activeTab} onChange={setActiveTab} />
      </div>
      <Table
        variant="default"
        data={(() => {
          const periodFilter = activeTab === 'all' ? null : activeTab;

          const filtered = (reports || []).filter(item => {
            if (periodFilter) {
              if (!item.period || String(item.period).toLowerCase() !== String(periodFilter).toLowerCase()) return false;
            }

            const matchesSearch = searchTerm
              ? Object.values(item).some(val => String(val).toLowerCase().includes(searchTerm.toLowerCase()))
              : true;
            if (!matchesSearch) return false;

            if (activeFilters.rating) {
              const avg = Math.round(Number(item.averageCSAT || 0));
              if (avg !== Number(activeFilters.rating)) return false;
            }

            if (activeFilters.startDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const start = new Date(activeFilters.startDate);
                if (itemDate < start) return false;
              } catch (e) {}
            }
            if (activeFilters.endDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const end = new Date(activeFilters.endDate);
                end.setHours(23,59,59,999);
                if (itemDate > end) return false;
              } catch (e) {}
            }

            return true;
          });

          return filtered.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);
        })()}
        columns={columns}
        title="CSAT Performance Reports"
        searchable
        searchPlaceholder="Search..."
        searchValue={searchTerm}
        onSearchChange={(e) => setSearchTerm(e.target.value)}
        filterComponent={FilterComponent}
        showFilter={showFilter}
        onShowFilterChange={setShowFilter}
        currentPage={currentPage}
        pageSize={itemsPerPage}
        totalItems={(() => {
          const periodFilter = activeTab === 'all' ? null : activeTab;
          return (reports || []).filter(item => {
            if (periodFilter) {
              if (!item.period || String(item.period).toLowerCase() !== String(periodFilter).toLowerCase()) return false;
            }
            const matchesSearch = searchTerm
              ? Object.values(item).some(val => String(val).toLowerCase().includes(searchTerm.toLowerCase()))
              : true;
            if (!matchesSearch) return false;
            if (activeFilters.rating) {
              const avg = Math.round(Number(item.averageCSAT || 0));
              if (avg !== Number(activeFilters.rating)) return false;
            }
            if (activeFilters.startDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const start = new Date(activeFilters.startDate);
                if (itemDate < start) return false;
              } catch (e) {}
            }
            if (activeFilters.endDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const end = new Date(activeFilters.endDate);
                end.setHours(23,59,59,999);
                if (itemDate > end) return false;
              } catch (e) {}
            }
            return true;
          }).length;
        })()}
        onPageChange={setCurrentPage}
        onPageSizeChange={setItemsPerPage}
        isLoading={false}
        emptyMessage="No CSAT reports found."
      />
    </>
  );
};

export default CoordinatorAdminCSATPerformanceReports;
