const TICKETS = [
  {
    id: 1,
    ticketNumber: "TCK-2025-001",
    employeeId: 1,
    employeeName: "Zoey Martinez",
    employeeDepartment: "Finance Department",
    subject: "Unable to Access Payroll System",
    category: "IT Support",
    subcategory: "System Access",
    priority: "High",
    description: "I cannot log into the payroll system. Getting error message: Invalid credentials. Need urgent access to process this month salary.",
    fileAttachments: [
      { name: "error_screenshot.png", url: "/uploads/error_screenshot.png", size: "245 KB", uploadedAt: "2025-06-01T09:15:00" }
    ],
    scheduleRequest: { date: "2025-06-02", time: "14:00", notes: "Available after 2 PM" },
    assignedDepartment: "IT Support",
    status: "Closed",
    assignedTo: 3,
    assignedToName: "Rumi Nakamura",
    coordinatorComment: "High priority - payroll system access is critical. Assign immediately.",
    reviewedBy: "Rumi Nakamura",
    reviewedById: 3,
    dateReviewed: "2025-06-01T10:00:00",
    dateAssignedToDepartment: "2025-06-01T10:30:00",
    timeToAssign: 1.25,
    createdAt: "2025-06-01T09:15:00",
    updatedAt: "2025-06-05T16:30:00",
    resolvedAt: "2025-06-04T14:20:00",
    closedAt: "2025-06-05T16:30:00",
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-02T09:15:00",
    slaStatus: "Resolved On Time",
    resolutionNotes: "Password reset performed. User credentials updated in Active Directory. Verified successful login.",
    csatRating: 5,
    csatComment: "Very quick response! Rumi was super helpful and got me back into the system within hours. Excellent service!",
    csatSubmittedAt: "2025-06-05T16:30:00",
  },
  {
    id: 2,
    ticketNumber: "TCK-2025-002",
    employeeId: 2,
    employeeName: "Mira Chen",
    employeeDepartment: "Marketing Department",
    subject: "Request New Software License",
    category: "Facilities & Equipment",
    subcategory: "Equipment Request",
    priority: "Medium",
    description: "Need Adobe Creative Cloud license for upcoming campaign. Current trial expires next week.",
    fileAttachments: [
      { name: "license_request_form.pdf", url: "/uploads/license_request.pdf", size: "1.2 MB", uploadedAt: "2025-06-02T10:30:00" }
    ],
    scheduleRequest: null,
    assignedDepartment: "IT Support",
    status: "Resolved",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: "Approved. Process license purchase through vendor.",
    reviewedBy: "Rumi Nakamura",
    reviewedById: 3,
    dateReviewed: "2025-06-02T14:00:00",
    dateAssignedToDepartment: "2025-06-02T14:30:00",
    timeToAssign: 4.0,
    createdAt: "2025-06-02T10:30:00",
    updatedAt: "2025-06-08T11:15:00",
    resolvedAt: "2025-06-08T11:15:00",
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-04T10:30:00",
    slaStatus: "SLA Breached",
    resolutionNotes: "Adobe Creative Cloud license procured and activated. User account configured with full access.",
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 3,
    ticketNumber: "TCK-2025-003",
    employeeId: 1,
    employeeName: "Zoey Martinez",
    employeeDepartment: "Finance Department",
    subject: "Office Space Too Cold",
    category: "Facilities & Equipment",
    subcategory: "Facilities Issue",
    priority: "Low",
    description: "The AC in Finance office area is set too cold. Temperature is uncomfortable for working. Can someone adjust it?",
    fileAttachments: [],
    scheduleRequest: { date: "2025-06-03", time: "10:00", notes: "Morning would be best" },
    assignedDepartment: "Facilities",
    status: "In Progress",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: "Standard facilities request. Assign to maintenance.",
    reviewedBy: "Bobby Kim",
    reviewedById: 4,
    dateReviewed: "2025-06-03T11:00:00",
    dateAssignedToDepartment: "2025-06-03T11:30:00",
    timeToAssign: 2.5,
    createdAt: "2025-06-03T09:00:00",
    updatedAt: "2025-06-03T15:20:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-06T09:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 4,
    ticketNumber: "TCK-2025-004",
    employeeId: 2,
    employeeName: "Mira Chen",
    employeeDepartment: "Marketing Department",
    subject: "Conference Room Booking System Not Working",
    category: "IT Support",
    subcategory: "Software Issue",
    priority: "Medium",
    description: "Cannot book conference rooms through the booking portal. System keeps timing out.",
    fileAttachments: [
      { name: "timeout_error.png", url: "/uploads/timeout_error.png", size: "189 KB", uploadedAt: "2025-06-04T08:45:00" }
    ],
    scheduleRequest: null,
    assignedDepartment: null,
    status: "Open",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-04T08:45:00",
    updatedAt: "2025-06-04T08:45:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-06T08:45:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 5,
    ticketNumber: "TCK-2025-005",
    employeeId: 1,
    employeeName: "Zoey Martinez",
    employeeDepartment: "Finance Department",
    subject: "Request for Standing Desk",
    category: "Facilities & Equipment",
    subcategory: "Equipment Request",
    priority: "Low",
    description: "Requesting a standing desk for ergonomic reasons. Current desk is causing back pain during long work hours.",
    fileAttachments: [
      { name: "medical_note.pdf", url: "/uploads/medical_note.pdf", size: "340 KB", uploadedAt: "2025-06-05T11:20:00" }
    ],
    scheduleRequest: null,
    assignedDepartment: "Facilities",
    status: "On Hold",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: "On hold pending budget approval for Q3. Will revisit next month.",
    reviewedBy: "Bobby Thompson",
    reviewedById: 4,
    dateReviewed: "2025-06-05T14:00:00",
    dateAssignedToDepartment: "2025-06-05T14:30:00",
    timeToAssign: 3.17,
    createdAt: "2025-06-05T11:20:00",
    updatedAt: "2025-06-06T10:15:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-08T11:20:00",
    slaStatus: "Within SLA",
    resolutionNotes: "Awaiting budget approval from Finance Director. Expected decision by end of June.",
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 6,
    ticketNumber: "TCK-2025-006",
    employeeId: 2,
    employeeName: "Mira Chen",
    employeeDepartment: "Marketing Department",
    subject: "Request for Personal Printer in Office",
    category: "Facilities & Equipment",
    subcategory: "Equipment Request",
    priority: "Low",
    description: "Would like a personal printer installed in my office for confidential marketing materials.",
    fileAttachments: [],
    scheduleRequest: null,
    assignedDepartment: "IT Support",
    status: "Rejected",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: "Does not meet company policy - use shared printers.",
    reviewedBy: "Rumi Nakamura",
    reviewedById: 3,
    dateReviewed: "2025-06-06T09:00:00",
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-06T08:30:00",
    updatedAt: "2025-06-06T09:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: "Company policy requires use of shared printing facilities for cost efficiency and environmental reasons. Personal printers are only approved for C-level executives. Please use the Marketing department printer on the 3rd floor.",
    dueDate: "2025-06-09T08:30:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 7,
    ticketNumber: "TCK-2025-007",
    employeeId: 1,
    employeeName: "Zoey Martinez",
    employeeDepartment: "Finance Department",
    subject: "Parking Space Assignment Issue",
    category: "Facilities & Equipment",
    subcategory: "Facilities Issue",
    priority: "Low",
    description: "My assigned parking space is being used by someone else. Need this resolved.",
    fileAttachments: [
      { name: "parking_photo.jpg", url: "/uploads/parking_photo.jpg", size: "1.8 MB", uploadedAt: "2025-06-07T07:45:00" }
    ],
    scheduleRequest: null,
    assignedDepartment: null,
    status: "Withdrawn",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-07T07:45:00",
    updatedAt: "2025-06-07T16:30:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: "2025-06-07T16:30:00",
    rejectionReason: null,
    dueDate: "2025-06-10T07:45:00",
    slaStatus: "Within SLA",
    resolutionNotes: "Issue resolved - employee spoke directly with security and the parking conflict was sorted out.",
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  // NEW TICKET TYPES - Updated Structure
  {
    id: 8,
    ticketNumber: "TCK-2025-008",
    employeeId: 2,
    employeeName: "Mira Chen",
    employeeDepartment: "Marketing Department",
    subject: "Laptop Hardware Issue - Battery Not Charging",
    category: "IT Support",
    subCategory: "Hardware Troubleshooting",
    priority: "High",
    description: "My work laptop battery is not charging. Tried different power outlets but still not working. Need urgent replacement as I have client presentations this week.",
    fileAttachments: [
      { name: "battery_status.png", url: "/uploads/battery_status.png", size: "156 KB", uploadedAt: "2025-06-08T09:30:00" }
    ],
    scheduleRequest: { date: "2025-06-09", time: "10:00", notes: "Morning preferred" },
    deviceType: "Laptop",
    softwareAffected: "",
    assignedDepartment: "IT Support",
    status: "In Progress",
    assignedTo: 3,
    assignedToName: "Rumi Nakamura",
    coordinatorComment: "High priority - user needs laptop for client work.",
    reviewedBy: "Rumi Nakamura",
    reviewedById: 3,
    dateReviewed: "2025-06-08T10:00:00",
    dateAssignedToDepartment: "2025-06-08T10:30:00",
    timeToAssign: 1.0,
    createdAt: "2025-06-08T09:30:00",
    updatedAt: "2025-06-08T14:20:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-09T09:30:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 9,
    ticketNumber: "TCK-2025-009",
    employeeId: 1,
    employeeName: "Zoey Martinez",
    employeeDepartment: "Finance Department",
    subject: "Returning Projector from Conference",
    category: "Asset Check In",
    subCategory: "Projector",
    priority: "Medium",
    description: "Returning the Epson PowerLite projector borrowed for last week's investor meeting. Device is in good condition.",
    fileAttachments: [],
    scheduleRequest: null,
    assetName: "Epson PowerLite 2247U",
    serialNumber: "PJ-2024-001",
    location: "Main Office - 2nd Floor",
    issueType: "Not Functioning",
    otherIssue: "",
    assignedDepartment: "Asset Management",
    status: "Resolved",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: "Standard asset return. Verify condition upon check-in.",
    reviewedBy: "Asset Manager",
    reviewedById: 5,
    dateReviewed: "2025-06-09T11:00:00",
    dateAssignedToDepartment: "2025-06-09T11:15:00",
    timeToAssign: 0.25,
    createdAt: "2025-06-09T10:45:00",
    updatedAt: "2025-06-09T15:00:00",
    resolvedAt: "2025-06-09T15:00:00",
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-10T10:45:00",
    slaStatus: "Resolved On Time",
    resolutionNotes: "Projector inspected and returned to inventory. Asset condition verified as good.",
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 10,
    ticketNumber: "TCK-2025-010",
    employeeId: 2,
    employeeName: "Mira Chen",
    employeeDepartment: "Marketing Department",
    subject: "Request Laptop for New Team Member",
    category: "Asset Check Out",
    subCategory: "Laptop",
    priority: "Medium",
    description: "Requesting a laptop for our new marketing coordinator starting next Monday. Prefer a Dell Latitude model if available.",
    fileAttachments: [],
    scheduleRequest: null,
    assetName: "Dell Latitude 5420",
    serialNumber: "DL-2024-001",
    location: "Main Office - 3rd Floor",
    expectedReturnDate: "2026-06-10",
    assignedDepartment: "Asset Management",
    status: "Open",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-10T08:00:00",
    updatedAt: "2025-06-10T08:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-12T08:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 11,
    ticketNumber: "TCK-2025-011",
    employeeId: 1,
    employeeName: "Zoey Martinez",
    employeeDepartment: "Finance Department",
    subject: "Q3 Budget Proposal - Finance Software Upgrade",
    category: "New Budget Proposal",
    subCategory: "Capital Expenses (CapEx)",
    priority: "High",
    description: "Requesting budget approval for upgrading our financial reporting software to the enterprise version. This will improve efficiency and provide better compliance reporting features.",
    fileAttachments: [
      { name: "parking_photo.jpg", url: "/uploads/parking_photo.jpg", size: "1.8 MB", uploadedAt: "2025-06-07T07:45:00" }
    ],
    scheduleRequest: null,
    budgetItems: [
      { costElement: "Software (long-term value like MS Office, Adobe Suite, Antivirus)", estimatedCost: "₱500,001 - ₱1,000,000" },
      { costElement: "Equipment", estimatedCost: "₱100,001 - ₱500,000" }
    ],
    totalBudget: 1500000,
    performanceStartDate: "2025-07-01",
    performanceEndDate: "2025-09-30",
    preparedBy: "Zoey Martinez",
    assignedDepartment: "Budget Management",
    status: "Open",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-11T09:00:00",
    updatedAt: "2025-06-11T09:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-18T09:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 12,
    ticketNumber: "TCK-2025-012",
    employeeId: 2,
    employeeName: "Mira Chen",
    employeeDepartment: "Marketing Department",
    subject: "Need Meeting Room for Team Brainstorming",
    category: "General Request",
    subCategory: "",
    priority: "Low",
    description: "Requesting to reserve Conference Room B for our marketing team brainstorming session. We'll need the room for the entire afternoon.",
    fileAttachments: [],
    scheduleRequest: { date: "2025-06-15", time: "13:00", notes: "Afternoon session, 1 PM to 5 PM" },
    assignedDepartment: "Facilities",
    status: "Open",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-12T10:00:00",
    updatedAt: "2025-06-12T10:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-15T10:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  // Ensure coverage for IT Support sub-categories used by the UI
  {
    id: 13,
    ticketNumber: "TCK-2025-013",
    employeeId: 1,
    employeeName: "Zoey Martinez",
    employeeDepartment: "Operations",
    subject: "Desktop won't boot",
    category: "IT Support",
    subCategory: "Desktop",
    priority: "High",
    description: "Desktop computer fails to boot; shows BIOS error code.",
    fileAttachments: [],
    scheduleRequest: null,
    assignedDepartment: "IT Support",
    status: "Open",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-13T09:00:00",
    updatedAt: "2025-06-13T09:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-15T09:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 14,
    ticketNumber: "TCK-2025-014",
    employeeId: 2,
    employeeName: "Mira Chen",
    employeeDepartment: "Sales",
    subject: "Laptop battery draining quickly",
    category: "IT Support",
    subCategory: "Laptop",
    priority: "Medium",
    description: "Laptop battery drops from 80% to 20% within 30 minutes.",
    fileAttachments: [],
    scheduleRequest: null,
    assignedDepartment: "IT Support",
    status: "In Progress",
    assignedTo: 3,
    assignedToName: "Rumi Nakamura",
    coordinatorComment: null,
    reviewedBy: "Rumi Nakamura",
    reviewedById: 3,
    dateReviewed: "2025-06-14T10:00:00",
    dateAssignedToDepartment: "2025-06-14T10:30:00",
    timeToAssign: 1.5,
    createdAt: "2025-06-14T09:30:00",
    updatedAt: "2025-06-14T11:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-16T09:30:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 15,
    ticketNumber: "TCK-2025-015",
    employeeId: 1,
    employeeName: "Zoey Martinez",
    employeeDepartment: "HR",
    subject: "Office printer jam",
    category: "IT Support",
    subCategory: "Printer",
    priority: "Low",
    description: "Printer in HR keeps jamming when printing multi-page documents.",
    fileAttachments: [],
    scheduleRequest: null,
    assignedDepartment: "Facilities",
    status: "Open",
    assignedTo: null,
    assignedToName: null,
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-15T08:00:00",
    updatedAt: "2025-06-15T08:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-18T08:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 16,
    ticketNumber: "TCK-2025-016",
    employeeId: 2,
    employeeName: "Mira Chen",
    employeeDepartment: "Engineering",
    subject: "Application crashes on startup",
    category: "IT Support",
    subCategory: "Application",
    priority: "High",
    description: "Internal app crashes immediately after launch with error code 0xC0000005.",
    fileAttachments: [],
    scheduleRequest: null,
    assignedDepartment: "IT Support",
    status: "Open",
    assignedTo: null,
    assignedToName: null,
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-16T09:00:00",
    updatedAt: "2025-06-16T09:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-18T09:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 17,
    ticketNumber: "TCK-2025-017",
    employeeId: 1,
    employeeName: "Zoey Martinez",
    employeeDepartment: "Support",
    subject: "OS update failed",
    category: "IT Support",
    subCategory: "Operating System",
    priority: "Medium",
    description: "Operating system update fails during installation with rollback.",
    fileAttachments: [],
    scheduleRequest: null,
    assignedDepartment: "IT Support",
    status: "Open",
    assignedTo: null,
    assignedToName: null,
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-17T10:00:00",
    updatedAt: "2025-06-17T10:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-19T10:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 18,
    ticketNumber: "TCK-2025-018",
    employeeId: 2,
    employeeName: "Mira Chen",
    employeeDepartment: "Sales",
    subject: "WiFi disconnects intermittently",
    category: "IT Support",
    subCategory: "WiFi",
    priority: "Medium",
    description: "Office WiFi drops connection every ~10 minutes in the sales area.",
    fileAttachments: [],
    scheduleRequest: null,
    assignedDepartment: "Network",
    status: "In Progress",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: null,
    reviewedBy: "Bobby Kim",
    reviewedById: 4,
    dateReviewed: "2025-06-18T09:30:00",
    dateAssignedToDepartment: "2025-06-18T10:00:00",
    timeToAssign: 0.5,
    createdAt: "2025-06-18T09:00:00",
    updatedAt: "2025-06-18T11:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-20T09:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 19,
    ticketNumber: "TCK-2025-019",
    employeeId: 1,
    employeeName: "Zoey Martinez",
    employeeDepartment: "Finance",
    subject: "VPN connection won't establish",
    category: "IT Support",
    subCategory: "VPN",
    priority: "High",
    description: "Cannot connect to corporate VPN from home network; authentication times out.",
    fileAttachments: [],
    scheduleRequest: null,
    assignedDepartment: "Network",
    status: "Open",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-19T08:30:00",
    updatedAt: "2025-06-19T08:30:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-21T08:30:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 20,
    ticketNumber: "TCK-2025-020",
    employeeId: 2,
    employeeName: "Mira Chen",
    employeeDepartment: "Legal",
    subject: "Password reset needed",
    category: "IT Support",
    subCategory: "Password Reset",
    priority: "High",
    description: "Locked out of account after multiple failed attempts; needs password reset.",
    fileAttachments: [],
    scheduleRequest: null,
    assignedDepartment: "IT Support",
    status: "New",
  assignedTo: 3,
  assignedToName: "Rumi Nakamura",
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-06-20T09:00:00",
    updatedAt: "2025-06-20T09:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-06-20T12:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
  {
    id: 21,
    ticketNumber: "TCK-2025-021",
    employeeId: 3,
    employeeName: "Alex Gomez",
    employeeDepartment: "IT Support",
    subject: "Network drive not mapping",
    category: "IT Support",
    subCategory: "Network",
    priority: "Medium",
    description: "Unable to access the shared network drive since this morning. Error shows 'Access Denied'. Need access for file retrieval.",
    fileAttachments: [],
    scheduleRequest: null,
    assignedDepartment: null,
    status: "Pending",
    assignedTo: null,
    assignedToName: null,
    coordinatorComment: null,
    reviewedBy: null,
    reviewedById: null,
    dateReviewed: null,
    dateAssignedToDepartment: null,
    timeToAssign: null,
    createdAt: "2025-10-25T09:00:00",
    updatedAt: "2025-10-25T09:00:00",
    resolvedAt: null,
    closedAt: null,
    withdrawnAt: null,
    rejectionReason: null,
    dueDate: "2025-10-26T17:00:00",
    slaStatus: "Within SLA",
    resolutionNotes: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
  },
];

// --- Migration / normalization helpers ---
const CATEGORY_MAPPINGS = {
  'Facilities & Equipment': 'Others',
  'Facilities': 'Others',
  // add other legacy -> canonical mappings here if needed
};

const normalizeCategory = (cat) => {
  if (!cat) return cat;
  return CATEGORY_MAPPINGS[cat] || cat;
};

const normalizeTicket = (t) => {
  const ticket = { ...t };
  // Normalize category
  if (ticket.category) ticket.category = normalizeCategory(ticket.category);
  // Normalize inconsistent subcategory key names (seed uses `subcategory` sometimes)
  if (ticket.subcategory && !ticket.subCategory) ticket.subCategory = ticket.subcategory;
  if (ticket.subCategory && !ticket.subcategory) ticket.subcategory = ticket.subCategory;
  return ticket;
};

// FORCE RESET / seed localStorage with normalized tickets (remove after first load if desired)
if (typeof window !== 'undefined') {
  // Normalize seed and force-assign to Rumi (ticket coordinator) so dev users
  // can view all tickets under the coordinator while editing.
  const normalized = TICKETS.map(t => {
    const nt = normalizeTicket(t);
    // Force coordinator assignment to Rumi (id: 3)
    nt.assignedTo = 3;
    nt.assignedToName = 'Rumi Nakamura';
    // Attach a coordinator-only review object so coordinator/system admin views
    // can show who reviewed the ticket and any coordinator notes without
    // confusing that with the assigned agent fields. Keep existing fields
    // for backward compatibility, but centralize review info here.
    nt.coordinatorReview = nt.coordinatorReview || {
      coordinatorId: nt.reviewedById || nt.assignedTo || null,
      coordinatorName: nt.reviewedBy || nt.assignedToName || null,
      comment: nt.coordinatorComment || null,
      reviewedAt: nt.dateReviewed || null,
      visibleTo: ['Ticket Coordinator', 'System Admin'],
    };
    return nt;
  });
  localStorage.setItem('tickets', JSON.stringify(normalized));
  console.log('🔄 FORCE RESET: Seeded tickets (normalized categories) - all assigned to Rumi (id:3)');
}

export const getEmployeeTickets = (employeeId) => {
  const stored = localStorage.getItem('tickets');
  let tickets = stored ? JSON.parse(stored) : TICKETS;

  // Normalize any legacy tickets and persist normalized version
  const normalized = tickets.map(normalizeTicket);
  // If normalization changed anything, write back
  if (JSON.stringify(normalized) !== JSON.stringify(tickets)) {
    localStorage.setItem('tickets', JSON.stringify(normalized));
    tickets = normalized;
  }

  return employeeId ? tickets.filter(t => t.employeeId === employeeId) : tickets;
};

export const getAllTickets = () => {
  return getEmployeeTickets();
};

export const getTicketByNumber = (ticketNumber) => {
  return getEmployeeTickets().find(t => t.ticketNumber === ticketNumber);
};

export const getTicketById = (id) => {
  return getEmployeeTickets().find(t => t.id === id);
};

export const getTicketsByStatus = (status) => {
  return getEmployeeTickets().filter(t => t.status === status);
};

export const getTicketsByAssignee = (assigneeId) => {
  return getEmployeeTickets().filter(t => t.assignedTo === assigneeId);
};

export const createTicket = (ticketData) => {
  const tickets = getEmployeeTickets();
  const year = new Date().getFullYear();
  const ticketCount = tickets.length + 1;
  const newTicket = {
    id: tickets.length > 0 ? Math.max(...tickets.map(t => t.id)) + 1 : 1,
    ticketNumber: `TCK-${year}-${String(ticketCount).padStart(3, "0")}`,
    status: "New",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    resolvedAt: null,
    closedAt: null,
    assignedTo: null,
    assignedToName: null,
    csatRating: null,
    csatComment: null,
    csatSubmittedAt: null,
    ...ticketData,
  };
  tickets.push(newTicket);
  localStorage.setItem("tickets", JSON.stringify(tickets));
  return newTicket;
};

// Alias for createTicket (for backward compatibility)
export const addNewEmployeeTicket = createTicket;

export const updateTicket = (ticketNumber, updates) => {
  const tickets = getEmployeeTickets();
  const index = tickets.findIndex(t => t.ticketNumber === ticketNumber);
  if (index !== -1) {
    tickets[index] = {
      ...tickets[index],
      ...updates,
      updatedAt: new Date().toISOString(),
    };
    if (updates.status === "Resolved" && !tickets[index].resolvedAt) {
      tickets[index].resolvedAt = new Date().toISOString();
    }
    if (updates.status === "Closed" && !tickets[index].closedAt) {
      tickets[index].closedAt = new Date().toISOString();
    }
    localStorage.setItem("tickets", JSON.stringify(tickets));
    return tickets[index];
  }
  return null;
};

// Append a comment to a ticket (local storage).
export const addComment = (ticketNumber, comment) => {
  const tickets = getEmployeeTickets();
  const idx = tickets.findIndex(t => t.ticketNumber === ticketNumber || t.ticket_number === ticketNumber || String(t.id) === String(ticketNumber));
  if (idx === -1) return null;
  const ticket = tickets[idx];
  // Ensure comments array exists
  ticket.comments = Array.isArray(ticket.comments) ? ticket.comments : (Array.isArray(ticket.comment) ? ticket.comment : []);
  // Normalize comment shape
  const c = {
    id: comment.id ?? Date.now(),
    comment: comment.comment ?? comment.message ?? comment.body ?? comment.text ?? '',
    created_at: comment.created_at ?? comment.createdAt ?? new Date().toISOString(),
    user: comment.user ?? comment.author ?? null,
    is_internal: comment.is_internal ?? comment.isInternal ?? false,
  };
  ticket.comments.push(c);
  ticket.updatedAt = new Date().toISOString();
  localStorage.setItem('tickets', JSON.stringify(tickets));
  return ticket;
};

export const submitCSAT = (ticketNumber, rating, comment) => {
  return updateTicket(ticketNumber, {
    csatRating: rating,
    csatComment: comment,
    csatSubmittedAt: new Date().toISOString(),
    status: "Closed",
  });
};

export default TICKETS;
