# Generated by Django 5.2.3 on 2025-10-01 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSystemRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='roles.role')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='systems.system')),
            ],
        ),
    ]
