# Generated by Django 5.2.4 on 2025-10-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_roles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
