# Generated by Django 5.2.4 on 2025-11-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_approved_at_user_approved_by_user_rejected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('requires_captcha', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Device Fingerprint',
                'verbose_name_plural': 'Device Fingerprints',
                'db_table': 'auth_device_fingerprint',
            },
        ),
        migrations.CreateModel(
            name='IPAddressRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IP Address Rate Limit',
                'verbose_name_plural': 'IP Address Rate Limits',
                'db_table': 'auth_ip_rate_limit',
            },
        ),
        migrations.CreateModel(
            name='RateLimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_attempt_threshold', models.IntegerField(default=10, help_text='Failed attempts per IP before blocking')),
                ('ip_block_duration_minutes', models.IntegerField(default=30, help_text='Minutes to block an IP')),
                ('device_attempt_threshold', models.IntegerField(default=5, help_text='Failed attempts per device before captcha')),
                ('device_captcha_threshold', models.IntegerField(default=8, help_text='Failed attempts per device before blocking')),
                ('device_block_duration_minutes', models.IntegerField(default=20, help_text='Minutes to block a device')),
                ('attempt_reset_hours', models.IntegerField(default=24, help_text='Hours before resetting attempt count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rate Limit Configuration',
                'verbose_name_plural': 'Rate Limit Configuration',
                'db_table': 'auth_rate_limit_config',
            },
        ),
    ]
