# Generated by Django 5.2.4 on 2025-11-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_approved_at_user_approved_by_user_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, choices=[('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=10, null=True),
        ),
    ]
