# Generated by Django 5.2.4 on 2025-11-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_devicefingerprint_ipaddressratelimit_ratelimitconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefingerprint',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipaddressratelimit',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicefingerprint',
            name='fingerprint_hash',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ipaddressratelimit',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='devicefingerprint',
            unique_together={('fingerprint_hash', 'user_email')},
        ),
        migrations.AlterUniqueTogether(
            name='ipaddressratelimit',
            unique_together={('ip_address', 'user_email')},
        ),
    ]
