# Generated by Django 5.2.4 on 2025-12-07 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_devicefingerprint_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rejected_by',
        ),
        migrations.AddField(
            model_name='user',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
