# Generated by Django 5.2.4 on 2025-11-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_roles', '0003_usersystemrole_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemrole',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
