# Generated by Django 5.2.4 on 2025-11-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_roles', '0004_usersystemrole_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemrole',
            name='last_logged_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
