# Generated by Django 5.2.4 on 2025-11-18 12:20

import system_roles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_roles', '0005_usersystemrole_last_logged_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystemrole',
            name='settings',
            field=models.JSONField(blank=True, default=system_roles.models.get_default_settings),
        ),
    ]
