# Generated by Django 5.2.3 on 2025-10-01 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='systems.system')),
            ],
            options={
                'unique_together': {('system', 'name')},
            },
        ),
    ]
