// Mock data for Coordinator's Owned Tickets
// These are tickets assigned to ticket coordinators

export const mockOwnedTickets = [
  {
    id: 101,
    ticket_number: 'TCK-2025-101',
    ticketNumber: 'TCK-2025-101',
    subject: 'Equipment Request - Logitech K380 Keyboard',
    description: 'Requesting checkout of Logitech K380 keyboard for design work. Expected usage period: 3 months. Location: Main Office - 3rd floor. Manager approval: Alice Johnson.',
    status: 'Open',
    priority: 'Low',
    priorityLevel: 'Low',
    category: 'Asset Check Out',
    subCategory: 'Peripheral Equipment',
    requester: 'Marc Cedric Mayoga',
    requester_name: 'Marc Cedric Mayoga',
    assigned_to: null,
    assignedTo: null,
    assigned_to_name: null,
    assignedToName: null,
    department: 'Asset Management',
    assignedDepartment: 'Asset Management',
    dateCreated: '2025-11-24T04:57:00Z',
    submit_date: '2025-11-24T04:57:00Z',
    created_at: '2025-11-24T04:57:00Z',
    updatedAt: '2025-12-01T13:59:48Z',
    update_date: '2025-12-01T13:59:48Z',
    lifecycle: 'Triage Ticket',
    slaStatus: 'On Time'
  },
  {
    id: 102,
    ticket_number: 'TCK-2025-102',
    ticketNumber: 'TCK-2025-102',
    subject: 'Software License Renewal - Microsoft Office',
    description: 'Need to renew Microsoft Office 365 licenses for 50 users in the Marketing department. Current licenses expire on December 31, 2025.',
    status: 'In Progress',
    priority: 'High',
    priorityLevel: 'High',
    category: 'IT Support',
    subCategory: 'Software License',
    requester: 'Sarah Johnson',
    requester_name: 'Sarah Johnson',
    assigned_to: null,
    assignedTo: null,
    assigned_to_name: null,
    assignedToName: null,
    department: 'IT Support',
    assignedDepartment: 'IT Support',
    dateCreated: '2025-11-20T10:30:00Z',
    submit_date: '2025-11-20T10:30:00Z',
    created_at: '2025-11-20T10:30:00Z',
    updatedAt: '2025-12-02T14:15:00Z',
    update_date: '2025-12-02T14:15:00Z',
    lifecycle: 'Resolve Ticket',
    slaStatus: 'Due Soon'
  },
  {
    id: 103,
    ticket_number: 'TCK-2025-103',
    ticketNumber: 'TCK-2025-103',
    subject: 'Network Access Request - New Department',
    description: 'Employee transferred to Finance department needs network access setup including VPN, shared drives, and email forwarding.',
    status: 'Open',
    priority: 'Medium',
    priorityLevel: 'Medium',
    category: 'IT Support',
    subCategory: 'Account Access',
    requester: 'Robert Chen',
    requester_name: 'Robert Chen',
    assigned_to: null,
    assignedTo: null,
    assigned_to_name: null,
    assignedToName: null,
    department: 'IT Support',
    assignedDepartment: 'IT Support',
    dateCreated: '2025-12-01T08:00:00Z',
    submit_date: '2025-12-01T08:00:00Z',
    created_at: '2025-12-01T08:00:00Z',
    updatedAt: '2025-12-03T09:30:00Z',
    update_date: '2025-12-03T09:30:00Z',
    lifecycle: 'Triage Ticket',
    slaStatus: 'On Time'
  },
  {
    id: 104,
    ticket_number: 'TCK-2025-104',
    ticketNumber: 'TCK-2025-104',
    subject: 'Laptop Replacement Request',
    description: 'Current laptop is 5 years old and experiencing performance issues. Requesting replacement with latest Dell Latitude model.',
    status: 'Pending',
    priority: 'Medium',
    priorityLevel: 'Medium',
    category: 'Asset Check Out',
    subCategory: 'Laptop',
    requester: 'Emily Rodriguez',
    requester_name: 'Emily Rodriguez',
    assigned_to: null,
    assignedTo: null,
    assigned_to_name: null,
    assignedToName: null,
    department: 'Asset Management',
    assignedDepartment: 'Asset Management',
    dateCreated: '2025-11-28T11:00:00Z',
    submit_date: '2025-11-28T11:00:00Z',
    created_at: '2025-11-28T11:00:00Z',
    updatedAt: '2025-12-02T16:45:00Z',
    update_date: '2025-12-02T16:45:00Z',
    lifecycle: 'Triage Ticket',
    slaStatus: 'Due Soon'
  },
  {
    id: 105,
    ticket_number: 'TCK-2025-105',
    ticketNumber: 'TCK-2025-105',
    subject: 'Printer Toner Replacement',
    description: 'HP LaserJet Pro M404n printer on 2nd floor is showing low toner warning. Please deliver replacement cartridge.',
    status: 'Resolved',
    priority: 'Low',
    priorityLevel: 'Low',
    category: 'Facilities',
    subCategory: 'Equipment Maintenance',
    requester: 'David Martinez',
    requester_name: 'David Martinez',
    assigned_to: null,
    assignedTo: null,
    assigned_to_name: null,
    assignedToName: null,
    department: 'Facilities',
    assignedDepartment: 'Facilities',
    dateCreated: '2025-11-25T14:20:00Z',
    submit_date: '2025-11-25T14:20:00Z',
    created_at: '2025-11-25T14:20:00Z',
    updatedAt: '2025-12-01T10:15:00Z',
    update_date: '2025-12-01T10:15:00Z',
    lifecycle: 'Finalize Ticket',
    slaStatus: 'On Time'
  },
  {
    id: 106,
    ticket_number: 'TCK-2025-106',
    ticketNumber: 'TCK-2025-106',
    subject: 'Password Reset - Multiple Users',
    description: 'Group of 5 users from Human Resources department require password resets due to security policy update.',
    status: 'In Progress',
    priority: 'High',
    priorityLevel: 'High',
    category: 'IT Support',
    subCategory: 'Account Security',
    requester: 'Linda Thompson',
    requester_name: 'Linda Thompson',
    assigned_to: null,
    assignedTo: null,
    assigned_to_name: null,
    assignedToName: null,
    department: 'IT Support',
    assignedDepartment: 'IT Support',
    dateCreated: '2025-12-02T09:00:00Z',
    submit_date: '2025-12-02T09:00:00Z',
    created_at: '2025-12-02T09:00:00Z',
    updatedAt: '2025-12-03T15:30:00Z',
    update_date: '2025-12-03T15:30:00Z',
    lifecycle: 'Resolve Ticket',
    slaStatus: 'On Time'
  },
  {
    id: 107,
    ticket_number: 'TCK-2025-107',
    ticketNumber: 'TCK-2025-107',
    subject: 'Conference Room AV System Setup',
    description: 'Setup and test audio/visual system in newly renovated conference room on 4th floor. Includes projector, screen, and sound system.',
    status: 'Open',
    priority: 'Medium',
    priorityLevel: 'Medium',
    category: 'Facilities',
    subCategory: 'Equipment Setup',
    requester: 'George Wilson',
    requester_name: 'George Wilson',
    assigned_to: null,
    assignedTo: null,
    assigned_to_name: null,
    assignedToName: null,
    department: 'Facilities',
    assignedDepartment: 'Facilities',
    dateCreated: '2025-11-30T13:45:00Z',
    submit_date: '2025-11-30T13:45:00Z',
    created_at: '2025-11-30T13:45:00Z',
    updatedAt: '2025-12-03T11:20:00Z',
    update_date: '2025-12-03T11:20:00Z',
    lifecycle: 'Triage Ticket',
    slaStatus: 'On Time'
  },
  {
    id: 108,
    ticket_number: 'TCK-2025-108',
    ticketNumber: 'TCK-2025-108',
    subject: 'Monitor Replacement for Dual Display Setup',
    description: 'Request replacement of broken monitor (27 inch) for developer workstation. Need dual display capability for coding work.',
    status: 'Open',
    priority: 'Medium',
    priorityLevel: 'Medium',
    category: 'Asset Check Out',
    subCategory: 'Monitor',
    requester: 'Alex Kumar',
    requester_name: 'Alex Kumar',
    assigned_to: null,
    assignedTo: null,
    assigned_to_name: null,
    assignedToName: null,
    department: 'Asset Management',
    assignedDepartment: 'Asset Management',
    dateCreated: '2025-12-03T10:00:00Z',
    submit_date: '2025-12-03T10:00:00Z',
    created_at: '2025-12-03T10:00:00Z',
    updatedAt: '2025-12-03T10:00:00Z',
    update_date: '2025-12-03T10:00:00Z',
    lifecycle: 'Triage Ticket',
    slaStatus: 'On Time'
  },
  {
    id: 109,
    ticket_number: 'TCK-2025-109',
    ticketNumber: 'TCK-2025-109',
    subject: 'Budget Approval - Q4 Marketing Campaign',
    description: 'Request budget approval for Q4 digital marketing campaign including social media ads, email marketing, and content creation.',
    status: 'Pending',
    priority: 'High',
    priorityLevel: 'High',
    category: 'Budget Request',
    subCategory: 'Marketing Expenses',
    requester: 'Patricia Lee',
    requester_name: 'Patricia Lee',
    assigned_to: null,
    assignedTo: null,
    assigned_to_name: null,
    assignedToName: null,
    department: 'Finance',
    assignedDepartment: 'Finance',
    dateCreated: '2025-11-29T09:30:00Z',
    submit_date: '2025-11-29T09:30:00Z',
    created_at: '2025-11-29T09:30:00Z',
    updatedAt: '2025-12-02T14:00:00Z',
    update_date: '2025-12-02T14:00:00Z',
    lifecycle: 'Triage Ticket',
    slaStatus: 'Due Soon'
  },
  {
    id: 110,
    ticket_number: 'TCK-2025-110',
    ticketNumber: 'TCK-2025-110',
    subject: 'Office Keys Replacement',
    description: 'Need replacement office keys. Lost original set from office 312. Includes desk, filing cabinet, and main entrance keys.',
    status: 'Resolved',
    priority: 'Low',
    priorityLevel: 'Low',
    category: 'Facilities',
    subCategory: 'Security',
    requester: 'Frank Anderson',
    requester_name: 'Frank Anderson',
    assigned_to: null,
    assignedTo: null,
    assigned_to_name: null,
    assignedToName: null,
    department: 'Facilities',
    assignedDepartment: 'Facilities',
    dateCreated: '2025-11-22T16:00:00Z',
    submit_date: '2025-11-22T16:00:00Z',
    created_at: '2025-11-22T16:00:00Z',
    updatedAt: '2025-11-27T11:30:00Z',
    update_date: '2025-11-27T11:30:00Z',
    lifecycle: 'Finalize Ticket',
    slaStatus: 'On Time'
  }
];

export const coordinatorTicketActions = [
  {
    id: 1,
    ticketId: 101,
    user: 'Jane Smith',
    role: 'Ticket Coordinator',
    action: 'Assigned',
    timestamp: '2025-12-01T13:59:48Z',
    badge: 'ASSIGNED'
  },
  {
    id: 2,
    ticketId: 102,
    user: 'Jane Smith',
    role: 'Ticket Coordinator',
    action: 'Status Changed to In Progress',
    timestamp: '2025-12-02T14:15:00Z',
    badge: 'IN_PROGRESS'
  },
  {
    id: 3,
    ticketId: 105,
    user: 'Jane Smith',
    role: 'Ticket Coordinator',
    action: 'Resolved',
    timestamp: '2025-12-01T10:15:00Z',
    badge: 'RESOLVED'
  },
  {
    id: 4,
    ticketId: 106,
    user: 'Jane Smith',
    role: 'Ticket Coordinator',
    action: 'Priority Updated to High',
    timestamp: '2025-12-02T09:00:00Z',
    badge: 'HIGH_PRIORITY'
  },
  {
    id: 5,
    ticketId: 110,
    user: 'Jane Smith',
    role: 'Ticket Coordinator',
    action: 'Finalized',
    timestamp: '2025-11-27T11:30:00Z',
    badge: 'FINALIZED'
  }
];

export const coordinatorMessages = [
  {
    id: 1,
    ticketId: 101,
    sender: 'TTS Support Team',
    role: 'TTS Agent',
    timestamp: '2025-12-01T14:30:00Z',
    time: '14:30',
    content: 'Barcode scanner in main office is not working. Please use the scanner from 2nd floor for asset tracking.'
  },
  {
    id: 2,
    ticketId: 101,
    sender: 'IT Admin',
    role: 'TTS Agent',
    timestamp: '2025-12-01T15:00:00Z',
    time: '15:00',
    content: 'Asset has been added to AMS system. Location code: 3F-DESIGN-042. Checkout approved.'
  },
  {
    id: 3,
    ticketId: 102,
    sender: 'Procurement Team',
    role: 'TTS Agent',
    timestamp: '2025-12-02T10:45:00Z',
    time: '10:45',
    content: 'License quotes received. Awaiting final approval for volume discount negotiation.'
  },
  {
    id: 4,
    ticketId: 106,
    sender: 'Security Team',
    role: 'TTS Agent',
    timestamp: '2025-12-02T14:00:00Z',
    time: '14:00',
    content: 'Password policy updated. Temporary credentials sent to all 5 users. They should change passwords on first login.'
  }
];

export const requesterMessages = [
  {
    id: 1,
    ticketId: 101,
    sender: 'Marc Cedric Mayoga',
    role: 'Requester',
    timestamp: '2025-11-24',
    time: '04:57',
    content: 'Hi, I need to request a Logitech K380 keyboard for my design work. I\'ll need it for approximately 3 months. I\'m located on the 3rd floor of the main office, and my manager Alice Johnson has already approved this request.',
    isOwn: false
  },
  {
    id: 2,
    ticketId: 101,
    sender: 'Jane Smith',
    role: 'Ticket Coordinator',
    timestamp: '2025-11-24',
    time: '09:15',
    content: 'Hello Marc, thank you for your request. I can see that your manager has approved this. Can you please confirm the specific return date? You mentioned approximately 3 months - would that be around March 1, 2026?',
    isOwn: true
  },
  {
    id: 3,
    ticketId: 101,
    sender: 'Marc Cedric Mayoga',
    role: 'Requester',
    timestamp: '2025-11-24',
    time: '10:30',
    content: 'Yes, March 1, 2026 would be the expected return date. Should I come to the asset office to pick it up, or will it be delivered to my desk?',
    isOwn: false
  },
  {
    id: 4,
    ticketId: 102,
    sender: 'Sarah Johnson',
    role: 'Requester',
    timestamp: '2025-11-20',
    time: '10:30',
    content: 'Hi, we need to renew Microsoft Office licenses for 50 users. Current licenses expire December 31st. Can you help with this?',
    isOwn: false
  },
  {
    id: 5,
    ticketId: 102,
    sender: 'Jane Smith',
    role: 'Ticket Coordinator',
    timestamp: '2025-11-20',
    time: '11:00',
    content: 'Hi Sarah, I\'ll help with the license renewal. Let me check the current licensing model and get quotes for the renewal.',
    isOwn: true
  },
  {
    id: 6,
    ticketId: 106,
    sender: 'Linda Thompson',
    role: 'Requester',
    timestamp: '2025-12-02',
    time: '09:00',
    content: 'Good morning, we need password resets for 5 HR team members due to our new security policy. Can this be expedited?',
    isOwn: false
  },
  {
    id: 7,
    ticketId: 106,
    sender: 'Jane Smith',
    role: 'Ticket Coordinator',
    timestamp: '2025-12-02',
    time: '09:15',
    content: 'Hi Linda, I\'ll prioritize this. Can you provide the list of user IDs? I\'ll coordinate with IT to process this today.',
    isOwn: true
  }
];
