import React, { useMemo, useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { FaEye, FaDownload } from 'react-icons/fa';
import CoordinatorAdminReportsLayout from '../reports/CoordinatorAdminReportsLayout';
import InputField from '../../../shared/components/InputField';
import ticketStyles from '../ticket-management/CoordinatorAdminTicketManagement.module.css';
import TablePagination from '../../../shared/table/TablePagination';

import reportTickets from '../../../mock-data/reportTickets.json';
import reportCSATPerformance from '../../../mock-data/reportCSATPerformance.json';
import reportSLACompliance from '../../../mock-data/reportSLACompliance.json';
import CoordinatorTicketFilter from '../../components/filters/CoordinatorTicketFilter';
import FilterPanel from '../../../shared/table/FilterPanel';

// Column factories for each report type
const columnsFor = {
  ticket: () => [
    { key: 'reportName', label: 'Report Name' },
    { key: 'period', label: 'Period' },
    { key: 'dateGenerated', label: 'Date Generated' },
    { key: 'status', label: 'Status' },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'totalTickets', label: 'Total Tickets' },
    { key: 'resolved', label: 'Resolved' },
    { key: 'pending', label: 'Pending' },
    { key: 'id', label: 'Actions' },
  ],
  csat: () => [
    { key: 'reportName', label: 'Report Name' },
    { key: 'period', label: 'Period' },
    { key: 'dateGenerated', label: 'Date Generated' },
    { key: 'status', label: 'Status' },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'totalResponses', label: 'Total Responses' },
    { key: 'averageCSAT', label: 'Average CSAT' },
    { key: 'satisfied', label: 'Satisfied' },
    { key: 'unsatisfied', label: 'Unsatisfied' },
    { key: 'id', label: 'Actions' },
  ],
  sla: () => [
    { key: 'reportName', label: 'Report Name' },
    { key: 'period', label: 'Period' },
    { key: 'dateGenerated', label: 'Date Generated' },
    { key: 'status', label: 'Status' },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'totalTickets', label: 'Total Tickets' },
    { key: 'onTime', label: 'On Time' },
    { key: 'dueSoon', label: 'Due Soon' },
    { key: 'overdue', label: 'Overdue' },
    { key: 'id', label: 'Actions' },
  ],
};

const datasets = {
  ticket: reportTickets,
  csat: reportCSATPerformance,
  sla: reportSLACompliance,
};

const defaultTabs = [
  { label: 'All', value: 'all' },
  { label: 'Daily', value: 'daily' },
  { label: 'Weekly', value: 'weekly' },
  { label: 'Monthly', value: 'monthly' },
  { label: 'Yearly', value: 'yearly' },
];

const CoordinatorAdminUnifiedReports = ({ reportType = 'ticket', title }) => {
  const tabs = defaultTabs;
  const data = useMemo(() => datasets[reportType] || [], [reportType]);
  const cols = useMemo(() => (columnsFor[reportType] || columnsFor.ticket)(), [reportType]);

  const [searchTerm, setSearchTerm] = useState('');
  const [activeFilters, setActiveFilters] = useState({ status: null, startDate: '', endDate: '' });
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const lastActiveRef = useRef(null);
  const navigate = useNavigate();

  useEffect(() => setCurrentPage(1), [searchTerm, activeFilters]);

  const applyFilters = (items, period) => {
    const periodFilter = period === 'all' ? null : period;
    return items.filter(item => {
      // period
      if (periodFilter) {
        if (!item.period || String(item.period).toLowerCase() !== String(periodFilter).toLowerCase()) return false;
      }

      // basic status/date filters
      if (activeFilters.status && activeFilters.status.label) {
        if (!item.status) return false;
        if (String(item.status).toLowerCase() !== String(activeFilters.status.label).toLowerCase()) return false;
      }
      if (activeFilters.startDate) {
        try {
          const itemDate = new Date(item.dateGenerated);
          const start = new Date(activeFilters.startDate);
          if (itemDate < start) return false;
        } catch (e) {}
      }
      if (activeFilters.endDate) {
        try {
          const itemDate = new Date(item.dateGenerated);
          const end = new Date(activeFilters.endDate);
          end.setHours(23,59,59,999);
          if (itemDate > end) return false;
        } catch (e) {}
      }

      // search across some common fields
      if (searchTerm) {
        const q = searchTerm.toLowerCase();
        const matches = (String(item.reportName || '') + ' ' + String(item.generatedBy || '')).toLowerCase();
        if (!matches.includes(q)) return false;
      }

      return true;
    });
  };

  const renderActions = (row) => (
    <div className={ticketStyles.actionButtonCont}>
      <button
        title="View"
        className={ticketStyles.actionButton}
        onClick={() => {
          try {
            const tf = String(row.period || 'daily').toLowerCase();
            const url = `/admin/reports/ticket/view?timeframe=${encodeURIComponent(tf)}&reportId=${encodeURIComponent(row.id || '')}&autoGen=1`;
            navigate(url);
          } catch (e) {
            const tf = String(row.period || 'daily').toLowerCase();
            const url = `/admin/reports/ticket/view?timeframe=${encodeURIComponent(tf)}&reportId=${encodeURIComponent(row.id || '')}&autoGen=1`;
            window.location.href = url;
          }
        }}
      >
        <FaEye />
      </button>
      <button title="Export" className={ticketStyles.actionButton} onClick={() => console.log('Export report:', row)}>
        <FaDownload />
      </button>
    </div>
  );

  const renderCell = (col, row) => {
    if (col.key === 'period') {
      return <span style={{ padding: '4px 12px', borderRadius: 6 }}>{row.period}</span>;
    }
    if (col.key === 'status') {
      return <span style={{ padding: '4px 12px', borderRadius: 6 }}>{row.status}</span>;
    }
    if (col.key === 'id') return renderActions(row);
    return row[col.key];
  };

  // render function passed to layout so active tab is provided
  const renderContent = () => (active) => {
    if (lastActiveRef.current !== active) {
      setTimeout(() => setCurrentPage(1), 0);
      lastActiveRef.current = active;
    }

    const filtered = applyFilters(data, active);
    const page = filtered.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

    return (
      <>
        <div className={ticketStyles.tableHeader}>
          <h2>{title || `${reportType.toUpperCase()} Reports`}</h2>
          <div className={ticketStyles.tableActions}>
            <InputField placeholder="Search..." value={searchTerm} onChange={e => setSearchTerm(e.target.value)} inputStyle={{ width: '260px' }} />
          </div>
        </div>

        <div className={ticketStyles.tableWrapper}>
          <table className={ticketStyles.table}>
            <thead>
              <tr>{cols.map(c => <th key={c.key}>{c.label}</th>)}</tr>
            </thead>
            <tbody>
              {page.length === 0 ? (
                <tr><td colSpan={cols.length} style={{ textAlign: 'center', padding: 40, color: '#6b7280', fontStyle: 'italic' }}>No data found.</td></tr>
              ) : (
                page.map((row, idx) => (
                  <tr key={row.id || idx}>
                    {cols.map(col => (
                      <td key={col.key} style={{ padding: '12px 16px' }}>{renderCell(col, row)}</td>
                    ))}
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <div className={ticketStyles.tablePagination}>
          <TablePagination currentPage={currentPage} totalItems={filtered.length} initialItemsPerPage={itemsPerPage} onPageChange={setCurrentPage} onItemsPerPageChange={setItemsPerPage} alwaysShow={true} />
        </div>
      </>
    );
  };

  return (
    <CoordinatorAdminReportsLayout title={title || 'Reports'} tabs={tabs} filter={<CoordinatorTicketFilter onApply={setActiveFilters} onReset={() => setActiveFilters({ status: null, startDate: '', endDate: '' })} initialFilters={activeFilters} />}>
      {renderContent()}
    </CoordinatorAdminReportsLayout>
  );
};

export default CoordinatorAdminUnifiedReports;
