import React, { useMemo, useState, useEffect, useRef } from 'react';
import { FaEye, FaDownload } from 'react-icons/fa';
import reportSLACompliance from '../../../../mock-data/reportSLACompliance.json';
import Table from '../../../../shared/table/Table';
import CoordinatorTicketFilter from '../../../components/filters/CoordinatorAdminTicketManagementFilter';
import Tabs from '../../../../shared/components/Tabs';

const getPeriodBadgeStyle = (period) => {
  const badgeStyles = {
    Daily: { backgroundColor: '#E0E7FF', color: '#4F46E5' },
    Weekly: { backgroundColor: '#F3E8FF', color: '#7C3AED' },
    Monthly: { backgroundColor: '#DCFCE7', color: '#22C55E' },
    Yearly: { backgroundColor: '#FEF3C7', color: '#F59E0B' },
  };
  return badgeStyles[period] || {};
};

const CoordinatorAdminSLAComplianceReports = () => {
  const tabs = [
    { label: 'All', value: 'all' },
    { label: 'Daily', value: 'daily' },
    { label: 'Weekly', value: 'weekly' },
    { label: 'Monthly', value: 'monthly' },
    { label: 'Yearly', value: 'yearly' },
  ];

  const reports = useMemo(() => reportSLACompliance, []);
  const [activeTab, setActiveTab] = useState(tabs[0]?.value || 'all');
  const [searchTerm, setSearchTerm] = useState('');
  const [activeFilters, setActiveFilters] = useState({ status: null, startDate: '', endDate: '' });
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const [showFilter, setShowFilter] = useState(false);

  const FilterComponent = () => (
    <CoordinatorTicketFilter
      key={showFilter ? "filter-shown" : "filter-hidden"}
      preset="ticketManagement"
      initialShow={showFilter}
      onApply={setActiveFilters}
      onReset={() => {
        setActiveFilters({ status: null, startDate: '', endDate: '' });
        setCurrentPage(1);
      }}
      initialFilters={activeFilters}
    />
  );

  const columns = [
    { key: 'reportName', label: 'Report Name', skeletonWidth: '120px' },
    {
      key: 'period',
      label: 'Period',
      skeletonWidth: '80px',
      render: (val) => (
        <span style={{
          display: 'inline-block',
          padding: '4px 12px',
          borderRadius: '4px',
          fontSize: '12px',
          fontWeight: 600,
          ...getPeriodBadgeStyle(val),
        }}>
          {val}
        </span>
      )
    },
    { key: 'dateGenerated', label: 'Date Generated', skeletonWidth: '130px' },
    {
      key: 'status',
      label: 'Status',
      skeletonWidth: '80px',
      render: (val) => (
        <span style={{
          display: 'inline-block',
          padding: '4px 12px',
          borderRadius: '4px',
          fontSize: '12px',
          fontWeight: 600,
          backgroundColor: '#DCFCE7',
          color: '#22C55E',
        }}>
          {val}
        </span>
      )
    },
    { key: 'generatedBy', label: 'Generated By', skeletonWidth: '100px' },
    { key: 'totalTickets', label: 'Total Tickets', skeletonWidth: '80px', render: (val) => <span style={{ fontWeight: 600 }}>{val}</span> },
    { key: 'onTime', label: 'On Time', skeletonWidth: '80px', render: (val) => <span style={{ color: '#22C55E', fontWeight: 600 }}>{val}</span> },
    { key: 'dueSoon', label: 'Due Soon', skeletonWidth: '80px', render: (val) => <span style={{ color: '#F59E0B', fontWeight: 600 }}>{val}</span> },
    { key: 'overdue', label: 'Overdue', skeletonWidth: '80px', render: (val) => <span style={{ color: '#EF4444', fontWeight: 600 }}>{val}</span> },
    {
      key: 'actions',
      label: 'Actions',
      skeletonWidth: '80px',
      render: (val, row) => (
        <>
          <button
            title="View"
            style={{ padding: '6px 10px', background: '#f9f9f9', border: '1px solid #ccc', borderRadius: '4px', cursor: 'pointer' }}
            onClick={() => console.log(`View report ${row.id}`)}
          >
            <FaEye size={12} />
          </button>
          <button
            title="Export"
            style={{ padding: '6px 10px', background: '#f9f9f9', border: '1px solid #ccc', borderRadius: '4px', cursor: 'pointer' }}
            onClick={() => console.log(`Export report ${row.id}`)}
          >
            <FaDownload size={12} />
          </button>
        </>
      )
    }
  ];

  useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm, activeFilters]);

  return (
    <>
      <div style={{ marginTop: 12, marginBottom: 8 }}>
        <Tabs tabs={tabs} active={activeTab} onChange={setActiveTab} />
      </div>
      <Table
        variant="default"
        data={(() => {
          const periodFilter = activeTab === 'all' ? null : activeTab;

          const filtered = (reports || []).filter(item => {
            if (periodFilter) {
              if (!item.period || String(item.period).toLowerCase() !== String(periodFilter).toLowerCase()) return false;
            }

            const matchesSearch = searchTerm
              ? (String(item.reportName || '').toLowerCase().includes(searchTerm.toLowerCase()) || String(item.generatedBy || '').toLowerCase().includes(searchTerm.toLowerCase()))
              : true;
            if (!matchesSearch) return false;

            if (activeFilters.status && activeFilters.status.label) {
              if (!item.status) return false;
              if (String(item.status).toLowerCase() !== String(activeFilters.status.label).toLowerCase()) return false;
            }
            if (activeFilters.startDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const start = new Date(activeFilters.startDate);
                if (itemDate < start) return false;
              } catch (e) {}
            }
            if (activeFilters.endDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const end = new Date(activeFilters.endDate);
                end.setHours(23,59,59,999);
                if (itemDate > end) return false;
              } catch (e) {}
            }
            return true;
          });

          return filtered.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);
        })()}
        columns={columns}
        title="SLA Compliance Reports"
        searchable
        searchPlaceholder="Search..."
        searchValue={searchTerm}
        onSearchChange={(e) => setSearchTerm(e.target.value)}
        filterComponent={FilterComponent}
        showFilter={showFilter}
        onShowFilterChange={setShowFilter}
        currentPage={currentPage}
        pageSize={itemsPerPage}
        totalItems={(() => {
          const periodFilter = activeTab === 'all' ? null : activeTab;
          return (reports || []).filter(item => {
            if (periodFilter) {
              if (!item.period || String(item.period).toLowerCase() !== String(periodFilter).toLowerCase()) return false;
            }
            const matchesSearch = searchTerm
              ? (String(item.reportName || '').toLowerCase().includes(searchTerm.toLowerCase()) || String(item.generatedBy || '').toLowerCase().includes(searchTerm.toLowerCase()))
              : true;
            if (!matchesSearch) return false;
            if (activeFilters.status && activeFilters.status.label) {
              if (!item.status) return false;
              if (String(item.status).toLowerCase() !== String(activeFilters.status.label).toLowerCase()) return false;
            }
            if (activeFilters.startDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const start = new Date(activeFilters.startDate);
                if (itemDate < start) return false;
              } catch (e) {}
            }
            if (activeFilters.endDate) {
              try {
                const itemDate = new Date(item.dateGenerated);
                const end = new Date(activeFilters.endDate);
                end.setHours(23,59,59,999);
                if (itemDate > end) return false;
              } catch (e) {}
            }
            return true;
          }).length;
        })()}
        onPageChange={setCurrentPage}
        onPageSizeChange={setItemsPerPage}
        isLoading={false}
        emptyMessage="No SLA compliance reports found."
      />
    </>
  );
};

export default CoordinatorAdminSLAComplianceReports;
