# Generated by Django 5.2.3 on 2025-06-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Closed', 'Closed'), ('Withdrawn', 'Withdrawn')], default='New', max_length=20),
        ),
    ]
