# Generated by Django 5.2.6 on 2025-09-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedEmployeeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company_id', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
