# Generated by Django 5.2.7 on 2025-10-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rejectedemployeeaudit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RejectedEmployeeAudit',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT Department', 'IT Department'), ('Asset Management', 'Asset Management'), ('Document Control', 'Document Control'), ('Finance & Budgeting', 'Finance & Budgeting'), ('Operations', 'Operations'), ('Facilities & Maintenance', 'Facilities & Maintenance'), ('Human Resources', 'Human Resources'), ('Administration', 'Administration')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(blank=True, choices=[('IT Department', 'IT Department'), ('Asset Management', 'Asset Management'), ('Document Control', 'Document Control'), ('Finance & Budgeting', 'Finance & Budgeting'), ('Operations', 'Operations'), ('Facilities & Maintenance', 'Facilities & Maintenance'), ('Human Resources', 'Human Resources'), ('Administration', 'Administration')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('On Process', 'On Process'), ('On Hold', 'On Hold'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
    ]
