# Generated by Django 5.2.7 on 2025-10-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_rejectedemployeeaudit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dynamic_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
