# Generated by Django 5.2.7 on 2025-10-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ticket_approved_by_ticket_asset_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requested_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
