# Generated by Django 5.2.7 on 2025-10-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ticket_requested_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('On Process', 'On Process'), ('On Hold', 'On Hold'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
    ]
