# Generated by Django 5.2.7 on 2025-10-17 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ticket_status_employeelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('IT Support', 'IT Support'), ('Asset Check In', 'Asset Check In'), ('Asset Check Out', 'Asset Check Out'), ('New Budget Proposal', 'New Budget Proposal'), ('Others', 'Others')], max_length=100)),
                ('visibility', models.CharField(choices=[('Employee', 'Employee'), ('Ticket Coordinator', 'Ticket Coordinator'), ('System Admin', 'System Admin')], max_length=50)),
                ('description', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
