# Generated by Django 5.2.7 on 2025-10-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_employee_department_alter_ticket_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department_input',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fiscal_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
