# Generated by Django 5.2.7 on 2025-10-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ticket_department_input_ticket_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
