# Generated by Django 5.2.7 on 2025-10-27 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ticket_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='employee_cookie_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='User ID from external cookie-auth system', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
