# Generated by Django 5.2.7 on 2025-11-01 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ticket_employee_cookie_id_alter_ticket_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='user_cookie_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='User ID from external cookie-auth system', null=True),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
