# Generated by Django 5.2.4 on 2025-12-05 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_ticket_date_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="HDTSUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hdts_user_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("company_id", models.CharField(db_index=True, max_length=8)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("profile_picture", models.URLField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "HDTS User",
                "verbose_name_plural": "HDTS Users",
                "ordering": ["-last_synced_at"],
                "indexes": [
                    models.Index(
                        fields=["hdts_user_id"], name="core_hdtsus_hdts_us_66bfa0_idx"
                    ),
                    models.Index(fields=["email"], name="core_hdtsus_email_107284_idx"),
                    models.Index(
                        fields=["company_id"], name="core_hdtsus_company_3134d0_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_hdtsus_status_02a057_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HDTSUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hdts_user_role_id", models.IntegerField(db_index=True, unique=True)),
                ("role_name", models.CharField(db_index=True, max_length=100)),
                ("role_id", models.IntegerField()),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hdts_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.hdtsuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "HDTS User Role",
                "verbose_name_plural": "HDTS User Roles",
                "ordering": ["-last_synced_at"],
                "indexes": [
                    models.Index(
                        fields=["hdts_user", "role_name"],
                        name="core_hdtsus_hdts_us_ce9620_idx",
                    ),
                    models.Index(
                        fields=["role_name"], name="core_hdtsus_role_na_267ed7_idx"
                    ),
                ],
                "unique_together": {("hdts_user", "role_name")},
            },
        ),
    ]
