# Generated by Django 5.2.4 on 2025-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ticket_date_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDTSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdts_user_id', models.IntegerField(db_index=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('company_id', models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('notified', models.BooleanField(default=False)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HDTS User',
                'verbose_name_plural': 'HDTS Users',
                'ordering': ['-last_synced_at'],
                'indexes': [models.Index(fields=['hdts_user_id'], name='core_hdtsus_hdts_us_66bfa0_idx'), models.Index(fields=['email'], name='core_hdtsus_email_107284_idx'), models.Index(fields=['company_id'], name='core_hdtsus_company_3134d0_idx'), models.Index(fields=['status'], name='core_hdtsus_status_02a057_idx')],
            },
        ),
    ]
