# Generated by Django 6.0 on 2025-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ticket_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
