# Generated by Django 5.2.4 on 2025-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_hdtsuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, choices=[('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company_id', models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True)),
                ('department', models.CharField(blank=True, choices=[('IT Department', 'IT Department'), ('Asset Department', 'Asset Department'), ('Budget Department', 'Budget Department')], max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='external_employee_images/')),
                ('role', models.CharField(default='Employee', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('notified', models.BooleanField(default=False)),
                ('external_employee_id', models.IntegerField(db_index=True, null=True, unique=True)),
                ('external_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'External Employee',
                'verbose_name_plural': 'External Employees',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['external_employee_id'], name='core_extern_externa_f2f285_idx'), models.Index(fields=['email'], name='core_extern_email_5d587b_idx'), models.Index(fields=['company_id'], name='core_extern_company_6027f9_idx')],
            },
        ),
    ]
