# Generated by Django 5.2.4 on 2025-12-05 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_hdtsuser_hdtsuserrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hdtsuser',
            old_name='is_staff',
            new_name='notified',
        ),
        migrations.RemoveField(
            model_name='hdtsuser',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='hdtsuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='hdtsuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='hdtsuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hdtsuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='hdtsuser',
            name='rejected_at',
        ),
        migrations.AddField(
            model_name='hdtsuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hdtsuser',
            name='role',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hdtsuser',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hdtsuser',
            name='company_id',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='hdtsuser',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hdtsuser',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='HDTSUserRole',
        ),
    ]
