# Generated by Django 6.0 on 2025-12-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_knowledgearticle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='created_by_external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='created_by_external_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
