# Generated by Django 6.0 on 2025-12-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_knowledgearticle_created_by_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgearticle',
            name='created_by',
        ),
    ]
