# Generated by Django 5.2.4 on 2025-12-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_is_staff_hdtsuser_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdtsuser',
            name='company_id',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hdtsuser',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hdtsuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hdtsuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hdtsuser',
            name='role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hdtsuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
    ]
