# Generated by Django 6.0 on 2025-12-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_knowledgearticle_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticleversion',
            name='content',
            field=models.TextField(blank=True, help_text='Snapshot of article description at this version', null=True),
        ),
    ]
