# Generated by Django 5.2.4 on 2025-10-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_extended_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
